SELECT TOP (1000) [customer_id]
      ,[age]
      ,[gender]
      ,[item_purchased]
      ,[category]
      ,[purchase_amount]
      ,[location]
      ,[size]
      ,[color]
      ,[season]
      ,[review_rating]
      ,[subscription_status]
      ,[shipping_type]
      ,[discount_applied]
      ,[previous_purchases]
      ,[payment_method]
      ,[frequency_of_purchases]
      ,[age_group]
      ,[purchase_frequency_days]
  FROM [CustomerBehavior].[dbo].[CustomerData]

  select * from CustomerData 

 ---For total revenue  generated by male vs female customers---
 select gender, SUM(purchase_amount) as revenue
 from CustomerData
 group by gender

 ----Customers used a discount but still spent more than the average purchase amount---
 select customer_id,purchase_amount
 from CustomerData 
 where discount_applied='Yes' and purchase_amount >=(select AVG(purchase_amount) from CustomerData)

 ---The top 5 products with the highest average review rating---
 select item_purchased,round(AVG(CAST(review_rating AS 
 DECIMAL(10,2))),2) AS "Average Product Rating"
 from CustomerData
 group by item_purchased
 order by avg(cast(review_rating As
 DECIMAL(10,2))) DESC;

 --- Compare the average Purchase Amounts between Standard and Express Shipping---

SELECT shipping_type,
AVG(purchase_amount) AS average_purchase_amount
FROM CustomerData
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;

--- Compare average spend and total revenue between subscribers and non-subscribers---

SELECT subscription_status,
AVG(purchase_amount) AS average_spend,
SUM(purchase_amount) AS total_revenue
FROM CustomerData
GROUP BY subscription_status;

---Which 5 products have the highest percentage of purchases with discounts applied---

SELECT TOP 5 item_purchased,
ROUND( 100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*),2) 
AS discount_percentage
FROM CustomerData
GROUP BY item_purchased
ORDER BY discount_percentage DESC;


--- Segment customers into New, Returning, and Loyal based on previous purchases---

SELECT CASE
WHEN previous_purchases = 0 THEN 'New'
WHEN previous_purchases BETWEEN 1 AND 5 THEN 'Returning'
ELSE 'Loyal'
END AS customer_segment,
COUNT(*) AS customer_count
FROM CustomerData
GROUP BY
CASE
WHEN previous_purchases = 0 THEN 'New'
WHEN previous_purchases BETWEEN 1 AND 5 THEN 'Returning'
ELSE 'Loyal'
END;


--- Top 3 most purchased products within each category---

WITH RankedProducts AS
(
    SELECT category,
           item_purchased,
           COUNT(*) AS total_purchases,
           ROW_NUMBER() OVER
           (
               PARTITION BY category
               ORDER BY COUNT(*) DESC
           ) AS rank_no
    FROM CustomerData
    GROUP BY category, item_purchased
)

SELECT category,item_purchased,total_purchases
FROM RankedProducts
WHERE rank_no <= 3;

-- Q9: Are repeat buyers (more than 5 previous purchases) also likely to subscribe

SELECT subscription_status,
COUNT(*) AS total_customers
FROM CustomerData
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- Q10: Revenue contribution of each age group

SELECT age_group,
SUM(purchase_amount) AS total_revenue
FROM CustomerData
GROUP BY age_group
ORDER BY total_revenue DESC;